-- Exemple de table (TABLACONTROLER) pour la DF
-- CREATION DE LA STRUCTURE DES DONNEES
DROP TABLE TABLACONTROLER ;
CREATE TABLE TABLACONTROLER 
(COL1 VARCHAR2(20), COL2 VARCHAR2(20), COL3 VARCHAR2(1), COL4 VARCHAR2(1), COL5 VARCHAR2(20));
-- INSERTION DES DONNEES
--  Cette table est issue d'une intégration de données non réussie !
INSERT INTO TABLACONTROLER VALUES ('EPINAY-SUR-SEINE', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('PARIS', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('VILLETANEUSE', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('EPINAY-SUR-SEINE', '', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('EPINAY SUR SEINE', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('PARIS', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('PARIS', '', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('PARIS', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('MARSEILLE', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('ORLY-VILLE', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('MARSEILLE', 'FRANC', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('PARYS', 'FR', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('EPINAY-SUR-SEINE', 'FRANCE', '1', '1', 'EUROPE');
INSERT INTO TABLACONTROLER VALUES ('PARIS', 'france', '1', '1', '');
INSERT INTO TABLACONTROLER VALUES ('Bruxelles', 'Belgique', '1', '1', 'europe');
INSERT INTO TABLACONTROLER VALUES ('MOSCOU', 'RUSSIE', '1', '1', 'ASIE');
INSERT INTO TABLACONTROLER VALUES ('ALGER', 'ALGERIE', '1', '1', 'AFRIQUE');
INSERT INTO TABLACONTROLER VALUES ('RABAT', 'MAROC', '1', '1', 'afrique');
INSERT INTO TABLACONTROLER VALUES ('TUNIS', 'TUNISIE', '1', '1', 'AFRIQUE');

COMMIT;
-- VISUALISATION DES DONNEES
SELECT * FROM TABLACONTROLER;
-- PRETRAITEMENT >> HOMOGENEISATION DES DONNEES : TOUT EN MAJUSCULE
UPDATE TABLACONTROLER SET COL1 = UPPER(COL1);
UPDATE TABLACONTROLER SET COL2 = UPPER(COL2);
UPDATE TABLACONTROLER SET COL5 = UPPER(COL5);
COMMIT;
-- VISUALISATION DES DONNEES AVEC DOUBLONS
SELECT * FROM TABLACONTROLER;

-- ====== Algorithme simplifié pour vérifier la DF entre 2 colonnes :

-- Eliminer les doubles et compter le nombre d'occurrences
-- SUPPRIMER LES DOUBLONS (COL1, COL2)
CREATE OR REPLACE VIEW LISTAVERIFIER_VP0 (COL1_CITY, COL2_COUNTRY) AS SELECT COL1, COL2 FROM TABLACONTROLER;

CREATE OR REPLACE VIEW LISTAVERIFIER_VP (COL1_CITY, COL2_COUNTRY) AS SELECT DISTINCT * FROM LISTAVERIFIER_VP0;
-- VISUALISATION DES DONNEES SANS DOUBLON
SELECT * FROM LISTAVERIFIER_VP ;

CREATE OR REPLACE VIEW VERIFDF_VP (COL1_CITY, NBROCC) AS
SELECT COL1_CITY, COUNT(*) FROM LISTAVERIFIER_VP GROUP BY COL1_CITY ORDER BY COL1_CITY;
-- VISUALISATION DU COMPTAGE DU NOMBRE D'OCCURRENCES POUR CHAQUE VALEUR DE COL1
SELECT * FROM VERIFDF_VP ;

-- Si le nombre d'occurrences maximal est supérieur à 1 Alors la DF n'est pas vérifiée !
-- CREATE OR REPLACE FUNCTION VerifDF ???
CREATE OR REPLACE FUNCTION VerifDF( p_COLONNE1 IN VARCHAR2, p_COLONNE2 IN VARCHAR2 )
RETURN VARCHAR2
IS
	RESULT VARCHAR2(50);
	NBRMAXOCC NUMBER(2);
	BEGIN
		  -- SELECT MAX(NBROCC) INTO NBRMAXOCC FROM VERIFDF_VP;	
		  SELECT MAX(NBROCC) AS MAXOCCUR INTO NBRMAXOCC FROM VERIFDF_VP;	
		  SELECT CASE WHEN NBRMAXOCC > 1 THEN 'FALSE' ELSE 'TRUE' END INTO RESULT FROM DUAL ;
		  RETURN(RESULT);
	END;
/
-- Tester la DF :  COL1 -DF- COL2
SELECT VerifDF(COL1, COL2) AS verificationDF FROM TABLACONTROLER;
SELECT VerifDF(COL2, COL5) AS verificationDF FROM TABLACONTROLER;
